# -*- mode: python ; coding: utf-8 -*-
import os
import sys
from PyInstaller.utils.hooks import collect_data_files

block_cipher = None

datas = []
datas += collect_data_files("app")

a = Analysis(
    ["run_backend.py"],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=[
        "app.main",
        "app.config.settings",
        "app.config.database",
        "app.models",
        "app.models.shift",
        "app.models.biometric_device",
        "app.models.employee",
        "app.models.employee_fingerprint",
        "app.models.app_user",
        "app.models.attendance",
        "app.models.attendance_record",
        "app.models.payroll_period",
        "app.models.overtime_request",
        "app.models.leave_excuse",
        "app.models.public_holiday",
        "app.models.audit_log",
        "app.routers",
        "app.routers.auth",
        "app.routers.employees",
        "app.routers.attendance",
        "app.routers.shifts",
        "app.routers.devices",

        "app.routers.websockets",
        "app.routers.reports",
        "app.middleware",
        "app.middleware.auth",
        "app.middleware.diagnostics",
        "app.services",
        "app.services.calculate_time",
        "app.services.device_controller",
        "app.services.zkteco_k40_controller",
        "app.services.safe_decode_time",
        "app.services.migration_runner",
        "app.usecases",
        "app.usecases.attendance",
        "app.usecases.employee",
        "app.usecases.overtime",
        "app.usecases.payroll",
        "app.utils",
        "app.utils.jwt_utils",
        "app.utils.password_utils",
        "app.utils.token_blacklist",
        "app.utils.logger",
        "app.schemas",
        "app.schemas.auth",
        "app.schemas.employee",
        "app.schemas.attendance",
        "app.schemas.shift",
        "app.schemas.device",
        "app.schemas.leave",
        "app.schemas.overtime",
        "app.schemas.payroll",
        "app.schemas.holiday",
        "app.schemas.audit",
        "app.schemas.reports",
        "passlib.handlers.bcrypt",
        "bcrypt",
        "jose",
        "jose.jwt",
        "jose.constants",
        "multipart",
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.middleware",
        "uvicorn.middleware.proxy_headers",
        "websockets",
        "websockets.legacy",
        "websockets.legacy.server",
        "websockets.legacy.client",
        "sqlalchemy",
        "sqlalchemy.sql.default_comparator",
        "psycopg2",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "numpy",
        "pandas",
        "PIL",
        "cv2",
        "scipy",
        "zmq",
        "notebook",
        "jupyter",
        "distributed",
        "bokeh",
        "plotly",
        "dash",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="backend_server",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
